import { redirect } from 'next/navigation';
import PracticeClient, { type PracticeExercise } from './PracticeClient';
import { getUserSession } from '@/lib/aws/auth-utils';
import { RecommendationRepository } from '@/lib/aws/repositories/recommendation.repository';
import { ExerciseRepository } from '@/lib/aws/repositories/exercise.repository';
import { UserRepository } from '@/lib/aws/repositories/user.repository';
import { AdaptiveGenerator } from '@/domains/typing/generators/AdaptiveGenerator';
import styles from './practice.module.css';

export default async function PracticePage() {
  const user = await getUserSession();

  if (!user) {
    redirect('/login');
  }

  let targetSkillId = null;
  const activeRec = await RecommendationRepository.getActiveRecommendation(user.id);
  const profile = await UserRepository.getProfile(user.id);
  const dna = await UserRepository.getTypingDNA(user.id);
  
  const grade = profile?.grade_level || 6;
  const name = profile?.display_name || 'Student';
  const xp = profile?.xp_total || 0;
  const weakKeys = dna?.weak_keys || {};
  const hasWeakKeys = Object.keys(weakKeys).length > 0;

  if (activeRec) {
    targetSkillId = activeRec.recommended_skill_id;
  }

  let exercise: PracticeExercise | null = null;
  const isBeltTest = (xp % 1000) > 900;

  if (isBeltTest && hasWeakKeys) {
    const passage = await AdaptiveGenerator.generateBeltTest(weakKeys, name, grade, 50);
    exercise = {
      id: 'belt-test',
      domain_id: '1',
      skill_ids: [],
      title: 'Belt Mastery Test',
      difficulty: 3,
      difficulty_metadata: {},
      content: {
        passage,
        hint: 'This is a Belt Test! It is longer and harder, testing all your weaknesses to prepare you for the next level.',
      },
      is_ai_generated: true,
      grade_level_min: 1,
      grade_level_max: 12,
      created_at: new Date().toISOString(),
    };
  } else if (activeRec?.recommended_exercise_id === 'ADAPTIVE_WEAKNESS_DRILL' || hasWeakKeys) {
    // If they have weak keys, we generate an adaptive drill either if explicitly recommended,
    // or as the default fallback instead of a boring static exercise.
    const passage = await AdaptiveGenerator.generatePassage(weakKeys, name, grade, 20);

    exercise = {
      id: `adaptive-drill-${Date.now()}`,
      domain_id: '1',
      skill_ids: [],
      title: 'Adaptive Weakness Drill',
      difficulty: 1,
      difficulty_metadata: {},
      content: {
        passage,
        hint: 'This drill was custom-generated by your AI Sensei to target characters you recently struggled with.',
      },
      is_ai_generated: true,
      grade_level_min: 1,
      grade_level_max: 12,
      created_at: new Date().toISOString(),
    };
  } else if (targetSkillId) {
    const domainExercises = await ExerciseRepository.getExercisesByDomain('1');
    exercise = (domainExercises as PracticeExercise[]).find((e) => (e.skill_ids || []).includes(targetSkillId)) ?? null;
  }

  // Final fallback to static if all else fails
  if (!exercise) {
    const domainExercises = await ExerciseRepository.getExercisesByDomain('1');
    const fallbackExercises = (domainExercises as PracticeExercise[]).filter(
      (e) => (e.grade_level_min || 1) <= grade && (e.grade_level_max || 12) >= grade
    );

    if (fallbackExercises.length > 0) {
      exercise = fallbackExercises[0];
    }
  }

  if (!exercise) {
    return (
      <div className={styles.page}>
        <div className={styles.empty}>
          <h2>No exercises found</h2>
          <p>Please check the database seeds.</p>
        </div>
      </div>
    );
  }

  return (
    <div className={styles.page}>
      <div className={styles.pageHeader}>
        <h1 className={styles.pageTitle}>Practice dojo</h1>
        <p className={styles.pageSubtitle}>Skill focus: {exercise.title}</p>
      </div>

      <PracticeClient studentId={user.id} exercise={exercise} />
    </div>
  );
}
