import { redirect } from 'next/navigation';
import PracticeClient, { type PracticeExercise } from './PracticeClient';
import { getUserSession } from '@/lib/aws/auth-utils';
import { RecommendationRepository } from '@/lib/aws/repositories/recommendation.repository';
import { ExerciseRepository } from '@/lib/aws/repositories/exercise.repository';
import { UserRepository } from '@/lib/aws/repositories/user.repository';
import { AdaptiveGenerator } from '@/domains/typing/generators/AdaptiveGenerator';
import { TYPING_SKILLS } from '@/domains/typing/catalog';
import styles from './practice.module.css';

export default async function PracticePage() {
  const user = await getUserSession();

  if (!user) {
    redirect('/login');
  }

  let targetSkillId = null;
  const activeRec = await RecommendationRepository.getActiveRecommendation(user.id);
  const profile = await UserRepository.getProfile(user.id);
  const dna = await UserRepository.getTypingDNA(user.id);
  
  const grade = profile?.grade_level || 6;
  const name = profile?.display_name || 'Student';
  const xp = profile?.xp_total || 0;
  const weakKeys = dna?.weak_keys || {};
  const hasWeakKeys = Object.keys(weakKeys).length > 0;

  if (activeRec) {
    targetSkillId = activeRec.recommended_skill_id;
  }

  let exercise: PracticeExercise | null = null;
  const isBeltTest = (xp % 1000) > 900;

  // Skill IDs that map to specialized AI generators
  const CODING_SYNTAX_SKILL_ID = '00000000-0000-0000-0000-000000000006';
  const NUMPAD_SKILL_ID = '00000000-0000-0000-0000-000000000007';
  const PUNCTUATION_SKILL_ID = '00000000-0000-0000-0000-000000000008';

  if (isBeltTest && hasWeakKeys) {
    const passage = await AdaptiveGenerator.generateBeltTest(weakKeys, name, grade, 50);
    exercise = {
      id: 'belt-test',
      domain_id: '1',
      skill_ids: [],
      title: 'Belt Mastery Test',
      difficulty: 3,
      difficulty_metadata: {},
      content: {
        passage,
        hint: 'This is a Belt Test! It is longer and harder, testing all your weaknesses to prepare you for the next level.',
      },
      is_ai_generated: true,
      grade_level_min: 1,
      grade_level_max: 12,
      created_at: new Date().toISOString(),
    };
  } else if (targetSkillId === CODING_SYNTAX_SKILL_ID) {
    const passage = await AdaptiveGenerator.generateCodingDrill(weakKeys, grade, 25);
    exercise = {
      id: 'coding-drill-adaptive',
      domain_id: '1',
      skill_ids: [CODING_SYNTAX_SKILL_ID],
      title: 'Coding Syntax Drill',
      difficulty: 4,
      difficulty_metadata: {},
      content: {
        passage,
        hint: 'Type this code snippet exactly — every bracket, semicolon, and symbol counts!',
      },
      is_ai_generated: true,
      grade_level_min: 1,
      grade_level_max: 12,
      created_at: new Date().toISOString(),
    };
  } else if (targetSkillId === NUMPAD_SKILL_ID) {
    const passage = await AdaptiveGenerator.generateNumpadDrill(25);
    exercise = {
      id: 'numpad-drill-adaptive',
      domain_id: '1',
      skill_ids: [NUMPAD_SKILL_ID],
      title: '10-Key Speed Drill',
      difficulty: 3,
      difficulty_metadata: {},
      content: {
        passage,
        hint: 'Focus on the number row. Accuracy over speed — build the muscle memory first.',
      },
      is_ai_generated: true,
      grade_level_min: 1,
      grade_level_max: 12,
      created_at: new Date().toISOString(),
    };
  } else if (targetSkillId === PUNCTUATION_SKILL_ID) {
    const passage = await AdaptiveGenerator.generatePunctuationDrill(name, grade, 20);
    exercise = {
      id: 'punctuation-drill-adaptive',
      domain_id: '1',
      skill_ids: [PUNCTUATION_SKILL_ID],
      title: 'Advanced Punctuation Drill',
      difficulty: 4,
      difficulty_metadata: {},
      content: {
        passage,
        hint: 'Pay close attention to semicolons, colons, hyphens, and quoted speech.',
      },
      is_ai_generated: true,
      grade_level_min: 1,
      grade_level_max: 12,
      created_at: new Date().toISOString(),
    };
  } else if (activeRec?.recommended_exercise_id === 'ADAPTIVE_WEAKNESS_DRILL' || hasWeakKeys) {
    // If they have weak keys, generate an adaptive drill as the default instead of a static exercise.
    const passage = await AdaptiveGenerator.generatePassage(weakKeys, name, grade, 20);

    exercise = {
      id: 'adaptive-drill',
      domain_id: '1',
      skill_ids: [],
      title: 'Adaptive Weakness Drill',
      difficulty: 1,
      difficulty_metadata: {},
      content: {
        passage,
        hint: 'This drill was custom-generated by your AI Sensei to target characters you recently struggled with.',
      },
      is_ai_generated: true,
      grade_level_min: 1,
      grade_level_max: 12,
      created_at: new Date().toISOString(),
    };
  } else if (targetSkillId) {
    const domainExercises = await ExerciseRepository.getExercisesByDomain('1');
    exercise = (domainExercises as PracticeExercise[]).find((e) => (e.skill_ids || []).includes(targetSkillId)) ?? null;
  }

  // Final fallback to static if all else fails
  if (!exercise) {
    const domainExercises = await ExerciseRepository.getExercisesByDomain('1');
    const fallbackExercises = (domainExercises as PracticeExercise[]).filter(
      (e) => (e.grade_level_min || 1) <= grade && (e.grade_level_max || 12) >= grade
    );

    if (fallbackExercises.length > 0) {
      exercise = fallbackExercises[0];
    }
  }

  if (!exercise) {
    return (
      <div className={styles.page}>
        <div className={styles.empty}>
          <h2>No exercises found</h2>
          <p>Please check the database seeds.</p>
        </div>
      </div>
    );
  }

  const targetSkill = TYPING_SKILLS.find((skill) => exercise.skill_ids.includes(skill.id));
  const mode = targetSkill
    ? (targetSkill.metadata as { practiceMode?: string }).practiceMode
    : 'accuracy';
  exercise.difficulty_metadata = {
    ...exercise.difficulty_metadata,
    practice_mode: mode,
  };

  return (
    <div className={styles.page}>
      <div className={styles.pageHeader}>
        <h1 className={styles.pageTitle}>Practice dojo</h1>
        <p className={styles.pageSubtitle}>Skill focus: {exercise.title}</p>
      </div>

      <PracticeClient studentId={user.id} exercise={exercise} />
    </div>
  );
}
