import type { Skill, SkillDependency } from '../../types/platform';

export const TYPING_DOMAIN_ID = '1';

export const TYPING_SKILL_IDS = {
  keyboardFamiliarity: 'typing-keyboard-familiarity',
  homeRow: 'typing-home-row',
  topRow: 'typing-top-row',
  bottomRow: 'typing-bottom-row',
  commonWords: 'typing-common-words',
  sentenceFluency: 'typing-sentence-fluency',
  capitalization: 'typing-capitalization',
  punctuation: 'typing-punctuation',
  numbers: 'typing-numbers',
  codingSyntax: 'typing-coding-syntax',
} as const;

export interface TypingSkillMetadata {
  icon: string;
  practiceMode: 'accuracy' | 'rhythm' | 'speed' | 'technique';
}

export const TYPING_SKILLS: Skill[] = [
  {
    id: TYPING_SKILL_IDS.keyboardFamiliarity,
    domain_id: TYPING_DOMAIN_ID,
    parent_skill_id: null,
    slug: 'keyboard-familiarity',
    name: 'Keyboard familiarity',
    description: 'Recognize and reach the keys with confidence.',
    grade_level_min: 1,
    grade_level_max: 12,
    difficulty_baseline: 1,
    is_active: true,
    metadata: { icon: '⌨', practiceMode: 'technique' } satisfies TypingSkillMetadata,
    created_at: '',
  },
  {
    id: TYPING_SKILL_IDS.homeRow,
    domain_id: TYPING_DOMAIN_ID,
    parent_skill_id: null,
    slug: 'home-row',
    name: 'Home row',
    description: 'Build your foundation on A S D F and J K L ;.',
    grade_level_min: 1,
    grade_level_max: 12,
    difficulty_baseline: 1,
    is_active: true,
    metadata: { icon: '⌂', practiceMode: 'technique' } satisfies TypingSkillMetadata,
    created_at: '',
  },
  {
    id: TYPING_SKILL_IDS.topRow,
    domain_id: TYPING_DOMAIN_ID,
    parent_skill_id: null,
    slug: 'top-row',
    name: 'Top row',
    description: 'Reach Q W E R T Y U I O P accurately.',
    grade_level_min: 1,
    grade_level_max: 12,
    difficulty_baseline: 2,
    is_active: true,
    metadata: { icon: '↑', practiceMode: 'accuracy' } satisfies TypingSkillMetadata,
    created_at: '',
  },
  {
    id: TYPING_SKILL_IDS.bottomRow,
    domain_id: TYPING_DOMAIN_ID,
    parent_skill_id: null,
    slug: 'bottom-row',
    name: 'Bottom row',
    description: 'Reach Z X C V B N M with control.',
    grade_level_min: 1,
    grade_level_max: 12,
    difficulty_baseline: 2,
    is_active: true,
    metadata: { icon: '↓', practiceMode: 'accuracy' } satisfies TypingSkillMetadata,
    created_at: '',
  },
  {
    id: TYPING_SKILL_IDS.commonWords,
    domain_id: TYPING_DOMAIN_ID,
    parent_skill_id: null,
    slug: 'common-words',
    name: 'Common words',
    description: 'Turn individual key reaches into familiar words.',
    grade_level_min: 1,
    grade_level_max: 12,
    difficulty_baseline: 2,
    is_active: true,
    metadata: { icon: 'Aa', practiceMode: 'rhythm' } satisfies TypingSkillMetadata,
    created_at: '',
  },
  {
    id: TYPING_SKILL_IDS.sentenceFluency,
    domain_id: TYPING_DOMAIN_ID,
    parent_skill_id: null,
    slug: 'sentence-fluency',
    name: 'Sentence fluency',
    description: 'Type complete thoughts smoothly and steadily.',
    grade_level_min: 2,
    grade_level_max: 12,
    difficulty_baseline: 3,
    is_active: true,
    metadata: { icon: '≋', practiceMode: 'rhythm' } satisfies TypingSkillMetadata,
    created_at: '',
  },
  {
    id: TYPING_SKILL_IDS.capitalization,
    domain_id: TYPING_DOMAIN_ID,
    parent_skill_id: null,
    slug: 'capitalization',
    name: 'Capitalization',
    description: 'Use Shift accurately without breaking your rhythm.',
    grade_level_min: 3,
    grade_level_max: 12,
    difficulty_baseline: 3,
    is_active: true,
    metadata: { icon: '⇧', practiceMode: 'technique' } satisfies TypingSkillMetadata,
    created_at: '',
  },
  {
    id: TYPING_SKILL_IDS.punctuation,
    domain_id: TYPING_DOMAIN_ID,
    parent_skill_id: null,
    slug: 'punctuation',
    name: 'Punctuation',
    description: 'Control commas, periods, quotes, and more.',
    grade_level_min: 3,
    grade_level_max: 12,
    difficulty_baseline: 4,
    is_active: true,
    metadata: { icon: '!', practiceMode: 'accuracy' } satisfies TypingSkillMetadata,
    created_at: '',
  },
  {
    id: TYPING_SKILL_IDS.numbers,
    domain_id: TYPING_DOMAIN_ID,
    parent_skill_id: null,
    slug: 'numbers',
    name: 'Numbers and symbols',
    description: 'Use the number row and common symbols accurately.',
    grade_level_min: 4,
    grade_level_max: 12,
    difficulty_baseline: 4,
    is_active: true,
    metadata: { icon: '123', practiceMode: 'speed' } satisfies TypingSkillMetadata,
    created_at: '',
  },
  {
    id: TYPING_SKILL_IDS.codingSyntax,
    domain_id: TYPING_DOMAIN_ID,
    parent_skill_id: null,
    slug: 'coding-syntax',
    name: 'Coding syntax',
    description: 'Practice brackets, braces, operators, and code punctuation.',
    grade_level_min: 6,
    grade_level_max: 12,
    difficulty_baseline: 5,
    is_active: true,
    metadata: { icon: '</>', practiceMode: 'accuracy' } satisfies TypingSkillMetadata,
    created_at: '',
  },
];

export const TYPING_DEPENDENCIES: SkillDependency[] = [
  { from_skill_id: TYPING_SKILL_IDS.keyboardFamiliarity, to_skill_id: TYPING_SKILL_IDS.homeRow, relationship: 'prerequisite_of' },
  { from_skill_id: TYPING_SKILL_IDS.homeRow, to_skill_id: TYPING_SKILL_IDS.topRow, relationship: 'prerequisite_of' },
  { from_skill_id: TYPING_SKILL_IDS.homeRow, to_skill_id: TYPING_SKILL_IDS.bottomRow, relationship: 'prerequisite_of' },
  { from_skill_id: TYPING_SKILL_IDS.topRow, to_skill_id: TYPING_SKILL_IDS.commonWords, relationship: 'prerequisite_of' },
  { from_skill_id: TYPING_SKILL_IDS.bottomRow, to_skill_id: TYPING_SKILL_IDS.commonWords, relationship: 'prerequisite_of' },
  { from_skill_id: TYPING_SKILL_IDS.commonWords, to_skill_id: TYPING_SKILL_IDS.sentenceFluency, relationship: 'prerequisite_of' },
  { from_skill_id: TYPING_SKILL_IDS.sentenceFluency, to_skill_id: TYPING_SKILL_IDS.capitalization, relationship: 'prerequisite_of' },
  { from_skill_id: TYPING_SKILL_IDS.sentenceFluency, to_skill_id: TYPING_SKILL_IDS.punctuation, relationship: 'prerequisite_of' },
  { from_skill_id: TYPING_SKILL_IDS.punctuation, to_skill_id: TYPING_SKILL_IDS.numbers, relationship: 'prerequisite_of' },
  { from_skill_id: TYPING_SKILL_IDS.numbers, to_skill_id: TYPING_SKILL_IDS.codingSyntax, relationship: 'prerequisite_of' },
];
